apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -zv redis.db.svc.cluster.local 6379; do echo "Waiting for Redis..."; sleep 3; done']
      containers:
        - name: go-app
          image: gimmeursocks/docker-k8s-challenge_app:latest  # my uploaded image
          ports:
            - containerPort: 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis.db.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
