apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      initContainers: # Only starts when redis is ready
        - name: check-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z redis.db.svc.cluster.local 6379; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: go-app
          image: gimmeursocks/docker-k8s-challenge_app:latest  # my uploaded image
          ports:
            - containerPort: 8080
          readinessProbe:  # Check if Redis is ready before start
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:  # Make sure it is working properly aswell
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: APP_PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis.db.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
