name: Build & Deploy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build with Docker Compose
        run: docker compose build
          
      - name: List Docker images
        run: docker images
        
      - name: Tag and Push Docker Image
        run: |
          docker tag docker-k8s-challenge-app:latest ${{ secrets.DOCKER_USERNAME }}/docker-k8s-challenge_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-k8s-challenge_app:latest

  deploy-and-test:
    needs: build-and-push
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        
      - name: Test the cluster
        run: kubectl get pods -A

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/namespaces.yaml
          kubectl apply -f k8s/go-deployment.yaml
          kubectl apply -f k8s/go-service-nodeport.yaml
          kubectl apply -f k8s/redis-pvc.yaml
          kubectl apply -f k8s/redis-statefulset.yaml
          kubectl apply -f k8s/redis-service.yaml
        
      - name: Test pods deployment
        run: kubectl get pods -A

      - name: Test service URLs
        run: |
          minikube service list
          echo "------------------opening the service------------------"
          kubectl get svc -A
      
      - name: Debug information
        run: |
          echo "Waiting for Go pod to be Ready..."
          kubectl wait --for=condition=ready pod -n app --timeout=90s --all
          kubectl get pods -n app
          kubectl describe pods -n app
          kubectl logs -n app $(kubectl get pods -n app -o name | head -1)
          kubectl describe svc -n app go-app-service
      
      - name: Test application via curl
        run: |
          MINIKUBE_IP=$(minikube ip)
          echo "Minikube IP: $MINIKUBE_IP"
          echo "Testing service on port 30080..."
          curl -v http://$MINIKUBE_IP:30080/
