name: Build & Push App Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build with Docker Compose
        run: docker compose build
          
      - name: List Docker images
        run: docker images
        
      - name: Tag and Push Docker Image
        run: |
          docker tag docker-k8s-challenge-app:latest ${{ secrets.DOCKER_USERNAME }}/docker-k8s-challenge_app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-k8s-challenge_app:latest

  # deploy:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Deploy to Kubernetes
  #       uses: azure/setup-kubectl@v3
        
  #     - name: Apply Kubernetes manifests
  #       run: |
  #         kubectl apply -f k8s/
